version: '3.8'
services:
  task-management-system:
    image: tms-image
    build: .
    container_name: tms-container
    ports:
      - "8080:8080"
    depends_on:
      - tms-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tms-db/task_management_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  tms-db:
    image: postgres:14-alpine
    container_name: db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=task_management_system