-- liquibase formatted sql

-- changeset liquibase:1

														-- USERS

create table if not exists users (
id int generated by default as identity not null primary key,
firstname varchar(100) not null,
lastname varchar(100) not null,
email varchar(100) not null unique,
birthday date,
password varchar(255) not null,
role varchar(50) not null default 'USER'
);

														-- TASKS

create table if not exists tasks (
id int generated by default as identity not null primary key,
title varchar(255) not null,
description varchar(1000) not null,
status varchar(20) not null default 'WAITING',
priority varchar(20) not null default 'MIDDLE',
author_id int not null references users(id) on delete cascade,
executor_id int references users(id) on delete cascade
);

														-- NOTES

create table if not exists notes (
id int generated by default as identity not null primary key,
task_id int not null references tasks(id) on delete cascade,
description varchar(1000) not null,
author_id int not null references users(id) on delete cascade,
write_date date not null
);